//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d2lPharma_Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class d2hpharmaassignmentEntities : DbContext
    {
        public d2hpharmaassignmentEntities()
            : base("name=d2hpharmaassignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblExpert> tblExperts { get; set; }
        public virtual DbSet<tblExperts_temp> tblExperts_temp { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }

        public System.Data.Entity.DbSet<d2lPharma_Assignment.Models.ExpertListViewModel> ExpertListViewModels { get; set; }
    }
}
